services:
  - type: web
    name: solo-leveling-game
    env: python
    buildCommand: ""
    startCommand: gunicorn main:app
    envVars:
      - key: FLASK_ENV
        value: production
    plan: free